apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictic-deployment
  labels:
    app: tictic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tictic
  template:
    metadata:
      labels:
        app: tictic
    spec:
      containers:
      - name: tictic
        image: sifytul/tictic:sha-89b2635d7cfd856d1f2e035194a7306414666810
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tictic-service
spec:
  selector:
    app: tictic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30090
  type: NodePort
